= Commanders extension Library for Arduino =

This is a library for Arduino to handle buttons, Dcc (Railroad Modeling), CAN or I2C bus, or serial interface to give orders.

In extra, directory, you will find

-DIO2 : this library MUST be installed. Commanders cannot operate without it. This is a fast access input/ouput ports librayr almost whithout changing classic Arduino syntax.
-mcp-can : if you need a CAN interface with Commanders, this library is able to work with any shield or circuit using MCP2515 chip. If you comment the line #define NO_CANCOMMANDER, you MUST use this library.
-DCC_Monitor_Accessories : This independant ino sketch is only a way to check the Dcc packets arriving to the Arduino. The DCC_decoder have been adapted to focus on accessories packets.

For more information about this library please visit us at
http://www.locoduino.org/spip.php?article165 in french or
http://git.framasoft.org/locoduino.org/Commanders/wikis/home for both french and english.

== License ==

Copyright (c) 2016 Locoduino.org. All right reserved.
Copyright (c) 2016 Thierry Paris.  All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA